---
- name: Update and reboot servers if necessary
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Update Debian-based systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
      register: update_result

    - name: Check if reboot is needed on Debian-based systems
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family == "Debian"

    - name: Reboot Debian-based systems if required
      reboot:
      when: ansible_os_family == "Debian" and reboot_required_file.stat.exists
      async: 400
      poll: 5

    - name: Update Fedora system
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      register: update_result

    - name: Check if reboot is needed on Fedora system
      command: needs-restarting -r
      ignore_errors: true
      register: needs_restart
      changed_when: needs_restart.rc == 1
      failed_when: needs_restart.rc not in [0, 1]
      when: ansible_os_family == "RedHat"

    - name: Reboot Fedora system if required
      reboot:
      when: ansible_os_family == "RedHat" and needs_restart.rc == 1
      async: 400
      poll: 5
